### ISSUE TITLE
MangoQuest V1.7.7 各种报错

### ISSUE THREAD

**Issue by shaokeyibb** [Cutiemango/MangoQuest#1]
1.记分板功能貌似无效，无法展示
2.NPC右键报错
MangoQuset处理NPCRightClickEvent事件时发生异常!
异常名称: java.lang.NullPointerException
异常说明: null
简易错误信息如下:
  位于mme.Cutiemango.MangoQuest.objects.QuestNPC.getMessage(QuestNPC.java:46)
  位于mme.Cutiemango.MangoQuest.manager.QuestNPCManager.getNPCMessage(QuestNPCManager.java:49)
  位于mme.Cutiemango.MangoQuest.manager.QuestBookGUIManager.openNPCInfo(QuestBookGUIManager.java:284)
  位于mme.Cutiemango.MangoQuest.listeners.PlayerListener.onNPCRightClick(PlayerListener.java:63)
  位于mme.Cutiemango.MangoQuest.listeners.MainListener.onNPCRightClick(MainListener.java:82)

**Comment by Cutiemango** [comment]
Bug has been fixed.
