### ISSUE TITLE
v1.7.7v2 bugs and recommendation

### ISSUE THREAD

**Issue by Bloody-Lotus** [Cutiemango/MangoQuest#2]
1. 如果在 [ 任務事件 ] 中的 [ 接受時觸發 ] 加入  [ 標題及副標題 ] 以及在 [ 完成時觸發 ] 加入 [ 標題 ]
 * 副標題的內容 * 不會在 =接受任務= 時出現 
而會在 =任務結束= 時出現

===================================================================
2. 有時候不能領取獎勵

===================================================================
3. 如在 [ 任務事件 ] 中的 [ 第N階段開始/完成 ] 加入 [ 標題 ] / [ 副標題 ]
=第N階段開始/完成= 時均不會出現任何 標題及副標題

===================================================================
建議: 任務獎勵中新增 *權限* 作為任務完成的獎勵

===================================================================
Bug 的情況難以以文字解說
如情況許可,請以RC 與TANG_N 聯絡 或電郵 tangtsun216@gmail.com 通知並進入本人的伺服器
伺服器版本為 1.11.2
IP為skyrealm.dlinkddns.com

**Comment by Cutiemango** [comment]
2. 建議附上BUG之錯誤代碼，以便修正

**Comment by Bloody-Lotus** [comment]
4. 有時候放棄任務的介面會出現多個 【放棄任務】及【取消】
如: 【放棄任務】【放棄任務】是，我要放棄
     【取消】【取消】不，我要反悔

**Comment by Bloody-Lotus** [comment]
建議2: 任務階段能否以分支方式完成
如:階段1{ 目標1 擊殺殭屍 || 目標2 擊殺山貓}
如完成目標1 ,則不用完成目標2 || 如完成目標2 ,則不用完成目標1
-> 獲得任務獎勵好感度+2        ||  ->獲得任務獎勵好感度-2

**Comment by Cutiemango** [comment]
建議的部分請利用建議表單回報。

**Comment by Cutiemango** [comment]
1.此功能經測試運作正常。
2.領取獎勵問題已有其他人回報，請於1.7.7v3版本釋出時再試試看。
3.若您是使用第1階段開始時觸發，請改用接受時觸發。
4.此BUG會在下次版本中修復。
若還需要更多支援請聯絡discord： Mango#5649
Thank you for reporting bugs.
